# Generated by Django 2.0.3 on 2018-05-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='shuffle_answer',
            new_name='shuffle_answers',
        ),
    ]
